name: Classroom Autograding Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  autograding-test:
    runs-on: ubuntu-latest
    steps:
      - name: A single test step
        run: echo "Workflow file is being read correctly!"